; Generated by PTT
(define (domain sokoban-typed)
(:requirements :typing :equality)
(:types LOC DIR BOX - object
)
(:predicates (at-robot ?l - LOC)
(at ?o - BOX ?l - LOC)
(adjacent ?l1 - LOC ?l2 - LOC ?d - DIR)
(clear ?l - LOC)
(stai_clear ?floc - LOC)
)
(:action move
:parameters ( ?from - LOC ?to - LOC ?dir - DIR)
:precondition (and (clear ?to)(at-robot ?from)(adjacent ?from ?to ?dir))
:effect (and (at-robot ?to)(not (at-robot ?from)))
)
(:action push
:parameters ( ?rloc - LOC ?bloc - LOC ?floc - LOC ?dir - DIR ?b - BOX)
:precondition (and (at-robot ?rloc)(at ?b ?bloc)(clear ?floc)(adjacent ?rloc ?bloc ?dir)(adjacent ?bloc ?floc ?dir))
:effect (and (at-robot ?bloc)(at ?b ?floc)(clear ?bloc)(not (at-robot ?rloc))(not (at ?b ?bloc))(not (clear ?floc)))
)
(:action push_mcr_move_mcr_move_mcr_push
:parameters ( ?rloc - LOC ?bloc - LOC ?floc - LOC ?dir - DIR ?b - BOX ?tox5 - LOC ?dirx6 - DIR ?tox7 - LOC ?flocx8 - LOC ?dirx9 - DIR)
:precondition (and (at-robot ?rloc)(at ?b ?bloc)(clear ?floc)(adjacent ?rloc ?bloc ?dir)(adjacent ?bloc ?floc ?dir)(clear ?tox5)(adjacent ?bloc ?tox5 ?dirx6)(clear ?tox7)(adjacent ?tox5 ?tox7 ?dir)(clear ?flocx8)(adjacent ?tox7 ?floc ?dirx9)(adjacent ?floc ?flocx8 ?dirx9)(stai_clear ?floc)(stai_clear ?tox5)(stai_clear ?tox7)(stai_clear ?flocx8)(not (= ?floc ?tox5))(not (= ?floc ?tox7))(not (= ?floc ?flocx8))(not (= ?tox5 ?tox7))(not (= ?tox5 ?flocx8))(not (= ?tox7 ?flocx8)))
:effect (and (clear ?bloc)(at-robot ?floc)(at ?b ?flocx8)(clear ?floc)(not (at-robot ?rloc))(not (at ?b ?bloc))(not (at-robot ?bloc))(not (at-robot ?tox5))(not (at-robot ?tox7))(not (at ?b ?floc))(not (clear ?flocx8)))
)
(:action push_mcr_push
:parameters ( ?rloc - LOC ?bloc - LOC ?floc - LOC ?dir - DIR ?b - BOX ?flocx5 - LOC)
:precondition (and (at-robot ?rloc)(at ?b ?bloc)(clear ?floc)(adjacent ?rloc ?bloc ?dir)(adjacent ?bloc ?floc ?dir)(clear ?flocx5)(adjacent ?floc ?flocx5 ?dir)(stai_clear ?floc)(stai_clear ?flocx5)(not (= ?floc ?flocx5)))
:effect (and (clear ?bloc)(at-robot ?floc)(at ?b ?flocx5)(clear ?floc)(not (at-robot ?rloc))(not (at ?b ?bloc))(not (at-robot ?bloc))(not (at ?b ?floc))(not (clear ?flocx5)))
)
)