; Generated by PTT
(define (problem ferry_14)(:domain ferry)
(:objects  car1 car2 car3 car4 car5 car6 car7 car8 car9 car10 - car
 loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 - location
)
(:init (empty-ferry)(at-ferry loc2)(at car1 loc1)(at car2 loc8)(at car3 loc7)(at car4 loc3)(at car5 loc5)(at car6 loc3)(at car7 loc5)(at car8 loc6)(at car9 loc7)(at car10 loc9)(stai_at car1 loc1)(stai_at car2 loc8)(stai_at car3 loc7)(stai_at car4 loc3)(stai_at car5 loc5)(stai_at car6 loc3)(stai_at car7 loc5)(stai_at car8 loc6)(stai_at car9 loc7)(stai_at car10 loc9)(stag_at car1 loc6)(stag_at car2 loc5)(stag_at car3 loc8)(stag_at car4 loc1)(stag_at car5 loc9)(stag_at car6 loc4)(stag_at car7 loc1)(stag_at car8 loc9)(stag_at car9 loc3)(stag_at car10 loc7))
(:goal (and  (at car1 loc6)(at car2 loc5)(at car3 loc8)(at car4 loc1)(at car5 loc9)(at car6 loc4)(at car7 loc1)(at car8 loc9)(at car9 loc3)(at car10 loc7)))
)