; Generated by PTT
(define (problem transport_17)(:domain transport)
(:objects  v1 v2 v3 v4 v5 - vehicle
 p1 p2 p3 p4 p5 p6 p7 p8 p9 - package
 l1 l2 l3 l4 l5 l6 l7 l8 l9 l10 - location
 c0 c1 c2 - size
)
(:init (capacity v1 c2)(capacity v2 c2)(capacity v3 c2)(capacity v4 c1)(capacity v5 c2)(capacity-predecessor c0 c1)(capacity-predecessor c1 c2)(at p1 l5)(at p2 l1)(at p3 l7)(at p4 l6)(at p5 l6)(at p6 l6)(at p7 l7)(at p8 l7)(at p9 l5)(at v1 l2)(at v2 l9)(at v3 l5)(at v4 l8)(at v5 l2)(road l2 l4)(road l10 l8)(road l2 l7)(road l3 l1)(road l7 l10)(road l6 l1)(road l9 l4)(road l8 l10)(road l10 l7)(road l10 l1)(road l4 l2)(road l4 l9)(road l1 l10)(road l7 l2)(road l1 l6)(road l2 l5)(road l1 l3)(road l5 l2)(road l6 l7)(road l7 l6)(road l1 l7)(road l7 l1)(road l5 l7)(road l7 l5)(road l2 l9)(road l9 l2)(road l8 l9)(road l9 l8)(road l7 l8)(road l8 l7)(road l3 l4)(road l4 l3)(stai_capacity v1 c2)(stai_capacity v2 c2)(stai_capacity v3 c2)(stai_capacity v4 c1)(stai_capacity v5 c2)(stai_at p1 l5)(stai_at p2 l1)(stai_at p3 l7)(stai_at p4 l6)(stai_at p5 l6)(stai_at p6 l6)(stai_at p7 l7)(stai_at p8 l7)(stai_at p9 l5)(stag_at p1 l6)(stag_at p2 l10)(stag_at p3 l6)(stag_at p4 l4)(stag_at p5 l1)(stag_at p6 l4)(stag_at p7 l5)(stag_at p8 l8)(stag_at p9 l9))
(:goal (and  (at p1 l6)(at p2 l10)(at p3 l6)(at p4 l4)(at p5 l1)(at p6 l4)(at p7 l5)(at p8 l8)(at p9 l9)))
)