; Generated by PTT
(define (problem miconic_01)(:domain miconic)
(:objects  p1 - passenger
 f1 f2 f3 f4 - floor
)
(:init (lift-at f1)(origin p1 f2)(destin p1 f3)(above f1 f2)(above f1 f3)(above f1 f4)(above f2 f3)(above f2 f4)(above f3 f4)(stai_origin p1 f2))
(:goal (and  (served p1)))
)