; Generated by PTT
(define (problem transport_10)(:domain transport)
(:objects  v1 v2 v3 v4 - vehicle
 p1 p2 p3 p4 p5 - package
 l1 l2 l3 l4 l5 l6 l7 l8 - location
 c0 c1 c2 - size
)
(:init (capacity v1 c2)(capacity v2 c2)(capacity v3 c2)(capacity v4 c1)(capacity-predecessor c0 c1)(capacity-predecessor c1 c2)(at p1 l2)(at p2 l6)(at p3 l8)(at p4 l1)(at p5 l8)(at v1 l8)(at v2 l7)(at v3 l3)(at v4 l8)(road l7 l4)(road l2 l4)(road l8 l1)(road l5 l4)(road l4 l6)(road l1 l8)(road l6 l4)(road l4 l2)(road l2 l3)(road l4 l5)(road l8 l2)(road l3 l2)(road l4 l7)(road l2 l8)(road l5 l8)(road l8 l5)(road l1 l3)(road l3 l1)(road l3 l5)(road l5 l3)(road l7 l8)(road l8 l7)(road l1 l5)(road l5 l1)(road l5 l7)(road l7 l5)(road l6 l8)(road l8 l6)(road l3 l6)(road l6 l3)(stai_capacity v1 c2)(stai_capacity v2 c2)(stai_capacity v3 c2)(stai_capacity v4 c1)(stai_at p1 l2)(stai_at p2 l6)(stai_at p3 l8)(stai_at p4 l1)(stai_at p5 l8)(stag_at p1 l4)(stag_at p2 l3)(stag_at p3 l4)(stag_at p4 l5)(stag_at p5 l5))
(:goal (and  (at p1 l4)(at p2 l3)(at p3 l4)(at p4 l5)(at p5 l5)))
)