; Generated by PTT
(define (domain ferry)
(:requirements :typing :equality)
(:types car - object
 location - object
)
(:predicates (at-ferry ?l - location)
(at ?c - car ?l - location)
(empty-ferry)
(on ?c - car)
(stai_at ?carx2 - car ?to - location)
(stag_at ?carx2 - car ?tox3 - location)
)
(:action sail
:parameters ( ?from - location ?to - location)
:precondition (and (at-ferry ?from)(not (at-ferry ?to)))
:effect (and (at-ferry ?to)(not (at-ferry ?from)))
)
(:action board
:parameters ( ?car - car ?loc - location)
:precondition (and (at ?car ?loc)(at-ferry ?loc)(empty-ferry))
:effect (and (on ?car)(not (at ?car ?loc))(not (empty-ferry)))
)
(:action debark
:parameters ( ?car - car ?loc - location)
:precondition (and (on ?car)(at-ferry ?loc))
:effect (and (at ?car ?loc)(empty-ferry)(not (on ?car)))
)
(:action sail_mcr_board_mcr_sail_mcr_sail_mcr_debark_mcr_sail
:parameters ( ?from - location ?to - location ?carx2 - car ?tox3 - location)
:precondition (and (at-ferry ?from)(not (at-ferry ?to))(at ?carx2 ?to)(empty-ferry)(not (at-ferry ?tox3))(stai_at ?carx2 ?to)(stag_at ?carx2 ?tox3)(not (= ?from ?to))(not (= ?from ?tox3))(not (= ?to ?tox3)))
:effect (and (at ?carx2 ?tox3)(empty-ferry)(at-ferry ?from)(not (at ?carx2 ?to))(not (at-ferry ?to))(not (on ?carx2))(not (at-ferry ?tox3)))
)
)