; Generated by PTT
(define (domain ferry)
(:requirements :typing :equality)
(:types car - object
 location - object
)
(:predicates (at-ferry ?l - location)
(at ?c - car ?l - location)
(empty-ferry)
(on ?c - car)
(stai_at ?carx2 - car ?to - location)
(stag_at ?carx2 - car ?to - location)
)
(:action sail
:parameters ( ?from - location ?to - location)
:precondition (and (at-ferry ?from)(not (at-ferry ?to)))
:effect (and (at-ferry ?to)(not (at-ferry ?from)))
)
(:action board
:parameters ( ?car - car ?loc - location)
:precondition (and (at ?car ?loc)(at-ferry ?loc)(empty-ferry))
:effect (and (on ?car)(not (at ?car ?loc))(not (empty-ferry)))
)
(:action debark
:parameters ( ?car - car ?loc - location)
:precondition (and (on ?car)(at-ferry ?loc))
:effect (and (at ?car ?loc)(empty-ferry)(not (on ?car)))
)
(:action sail_mcr_board_mcr_sail
:parameters ( ?from - location ?to - location ?carx2 - car)
:precondition (and (at-ferry ?from)(not (at-ferry ?to))(at ?carx2 ?to)(empty-ferry)(stai_at ?carx2 ?to)(not (= ?from ?to)))
:effect (and (on ?carx2)(at-ferry ?from)(not (at ?carx2 ?to))(not (empty-ferry))(not (at-ferry ?to)))
)
(:action sail_mcr_debark_mcr_sail
:parameters ( ?from - location ?to - location ?carx2 - car)
:precondition (and (at-ferry ?from)(not (at-ferry ?to))(on ?carx2)(stag_at ?carx2 ?to)(not (= ?from ?to)))
:effect (and (at ?carx2 ?to)(empty-ferry)(at-ferry ?from)(not (on ?carx2))(not (at-ferry ?to)))
)
)