; Generated by PTT
(define (problem blocksworld_20)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 b16 b17 b18 b19 b20 - object
)
(:init (arm-empty)(clear b12)(on b12 b17)(on b17 b14)(on-table b14)(clear b5)(on-table b5)(clear b3)(on b3 b15)(on b15 b20)(on b20 b2)(on b2 b11)(on b11 b6)(on b6 b19)(on b19 b8)(on b8 b7)(on b7 b10)(on b10 b4)(on b4 b18)(on b18 b13)(on b13 b9)(on b9 b16)(on b16 b1)(on-table b1)(stag_on b10 b12)(stag_on b12 b18)(stag_on b18 b14)(stag_on b14 b1)(stag_on b1 b4)(stag_on b4 b19)(stag_on b19 b5)(stag_on b15 b20)(stag_on b20 b2)(stag_on b2 b3)(stag_on b3 b8)(stag_on b8 b6)(stag_on b13 b7)(stag_on b7 b9)(stag_on b9 b11))
(:goal (and  (clear b17)(on-table b17)(clear b10)(on b10 b12)(on b12 b18)(on b18 b14)(on b14 b1)(on b1 b4)(on b4 b19)(on b19 b5)(on-table b5)(clear b16)(on-table b16)(clear b15)(on b15 b20)(on b20 b2)(on b2 b3)(on b3 b8)(on b8 b6)(on-table b6)(clear b13)(on b13 b7)(on b7 b9)(on b9 b11)(on-table b11)))
)