; Generated by PTT
(define (domain termes)
(:requirements :typing :equality)
(:types numb - object
 position - object
)
(:predicates (height ?p - position ?h - numb)
(at ?p - position)
(has-block)
(SUCC ?n1 - numb ?n2 - numb)
(NEIGHBOR ?p1 - position ?p2 - position)
(IS-DEPOT ?p - position)
)
(:action move
:parameters ( ?from - position ?to - position ?h - numb)
:precondition (and (at ?from)(NEIGHBOR ?from ?to)(height ?from ?h)(height ?to ?h))
:effect (and (not (at ?from))(at ?to))
)
(:action move-up
:parameters ( ?from - position ?hfrom - numb ?to - position ?hto - numb)
:precondition (and (at ?from)(NEIGHBOR ?from ?to)(height ?from ?hfrom)(height ?to ?hto)(SUCC ?hto ?hfrom))
:effect (and (not (at ?from))(at ?to))
)
(:action move-down
:parameters ( ?from - position ?hfrom - numb ?to - position ?hto - numb)
:precondition (and (at ?from)(NEIGHBOR ?from ?to)(height ?from ?hfrom)(height ?to ?hto)(SUCC ?hfrom ?hto))
:effect (and (not (at ?from))(at ?to))
)
(:action place-block
:parameters ( ?rpos - position ?bpos - position ?hbefore - numb ?hafter - numb)
:precondition (and (at ?rpos)(NEIGHBOR ?rpos ?bpos)(height ?rpos ?hbefore)(height ?bpos ?hbefore)(SUCC ?hafter ?hbefore)(has-block)(not (IS-DEPOT ?bpos)))
:effect (and (not (height ?bpos ?hbefore))(height ?bpos ?hafter)(not (has-block)))
)
(:action remove-block
:parameters ( ?rpos - position ?bpos - position ?hbefore - numb ?hafter - numb)
:precondition (and (at ?rpos)(NEIGHBOR ?rpos ?bpos)(height ?rpos ?hafter)(height ?bpos ?hbefore)(SUCC ?hbefore ?hafter)(not (has-block)))
:effect (and (not (height ?bpos ?hbefore))(height ?bpos ?hafter)(has-block))
)
(:action create-block
:parameters ( ?p - position)
:precondition (and (at ?p)(not (has-block))(IS-DEPOT ?p))
:effect (and (has-block))
)
(:action destroy-block
:parameters ( ?p - position)
:precondition (and (at ?p)(has-block)(IS-DEPOT ?p))
:effect (and (not (has-block)))
)
(:action remove-block_mcr_move_mcr_place-block
:parameters ( ?rpos - position ?bpos - position ?hbefore - numb ?hafter - numb ?tox4 - position ?bposx3x5 - position)
:precondition (and (at ?rpos)(NEIGHBOR ?rpos ?bpos)(height ?rpos ?hafter)(height ?bpos ?hbefore)(SUCC ?hbefore ?hafter)(not (has-block))(NEIGHBOR ?rpos ?tox4)(height ?tox4 ?hafter)(NEIGHBOR ?tox4 ?bposx3x5)(height ?bposx3x5 ?hafter)(not (IS-DEPOT ?bposx3x5)))
:effect (and (height ?bpos ?hafter)(at ?tox4)(height ?bposx3x5 ?hbefore)(not (height ?bpos ?hbefore))(not (at ?rpos))(not (height ?bposx3x5 ?hafter))(not (has-block)))
)
(:action move-up_mcr_place-block_mcr_move-down
:parameters ( ?from - position ?hfrom - numb ?to - position ?hto - numb ?bposx4 - position ?hafterx5 - numb ?tox6 - position)
:precondition (and (at ?from)(NEIGHBOR ?from ?to)(height ?from ?hfrom)(height ?to ?hto)(SUCC ?hto ?hfrom)(NEIGHBOR ?to ?bposx4)(height ?bposx4 ?hto)(SUCC ?hafterx5 ?hto)(has-block)(not (IS-DEPOT ?bposx4))(NEIGHBOR ?to ?tox6)(height ?tox6 ?hfrom))
:effect (and (height ?bposx4 ?hafterx5)(at ?tox6)(not (at ?from))(not (height ?bposx4 ?hto))(not (has-block))(not (at ?to)))
)
)