; Generated by PTT
(define (domain miconic)
(:requirements :typing :equality)
(:types passenger - object
 floor - object
)
(:predicates (origin ?person - passenger ?floor - floor)
(destin ?person - passenger ?floor - floor)
(above ?floor1 - floor ?floor2 - floor)
(boarded ?person - passenger)
(served ?person - passenger)
(lift-at ?floor - floor)
(stai_origin ?px2 - passenger ?f2 - floor)
)
(:action board
:parameters ( ?f - floor ?p - passenger)
:precondition (and (lift-at ?f)(origin ?p ?f))
:effect (and (boarded ?p)(not (origin ?p ?f)))
)
(:action depart
:parameters ( ?f - floor ?p - passenger)
:precondition (and (lift-at ?f)(destin ?p ?f)(boarded ?p))
:effect (and (not (boarded ?p))(served ?p))
)
(:action up
:parameters ( ?f1 - floor ?f2 - floor)
:precondition (and (lift-at ?f1)(above ?f1 ?f2))
:effect (and (lift-at ?f2)(not (lift-at ?f1)))
)
(:action down
:parameters ( ?f1 - floor ?f2 - floor)
:precondition (and (lift-at ?f1)(above ?f2 ?f1))
:effect (and (lift-at ?f2)(not (lift-at ?f1)))
)
(:action up_mcr_board_mcr_down
:parameters ( ?f1 - floor ?f2 - floor ?px2 - passenger)
:precondition (and (lift-at ?f1)(above ?f1 ?f2)(origin ?px2 ?f2)(stai_origin ?px2 ?f2))
:effect (and (boarded ?px2)(lift-at ?f1)(not (origin ?px2 ?f2))(not (lift-at ?f2)))
)
)