; Generated by PTT
(define (problem blocksworld_02)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 - object
)
(:init (arm-empty)(clear b3)(on b3 b1)(on-table b1)(clear b2)(on b2 b4)(on b4 b5)(on-table b5)(stag_on b2 b5)(stag_on b5 b4)(stag_on b4 b3)(stag_on b3 b1))
(:goal (and  (clear b2)(on b2 b5)(on b5 b4)(on b4 b3)(on b3 b1)(on-table b1)))
)