; Generated by PTT
(define (problem blocksworld_05)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 - object
)
(:init (arm-empty)(clear b8)(on b8 b5)(on b5 b7)(on b7 b2)(on b2 b4)(on b4 b1)(on b1 b3)(on b3 b6)(on-table b6)(stag_on b3 b8)(stag_on b8 b2)(stag_on b2 b1)(stag_on b1 b4)(stag_on b4 b6)(stag_on b7 b5))
(:goal (and  (clear b3)(on b3 b8)(on b8 b2)(on b2 b1)(on b1 b4)(on b4 b6)(on-table b6)(clear b7)(on b7 b5)(on-table b5)))
)