; Generated by PTT
(define (problem blocksworld_10)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - object
)
(:init (arm-empty)(clear b4)(on b4 b5)(on b5 b2)(on b2 b8)(on b8 b1)(on b1 b11)(on b11 b10)(on b10 b3)(on b3 b12)(on b12 b9)(on b9 b7)(on b7 b6)(on-table b6)(stag_on b4 b1)(stag_on b1 b12)(stag_on b12 b11)(stag_on b8 b7)(stag_on b7 b3)(stag_on b3 b9)(stag_on b9 b6)(stag_on b6 b5)(stag_on b5 b10)(stag_on b10 b2))
(:goal (and  (clear b4)(on b4 b1)(on b1 b12)(on b12 b11)(on-table b11)(clear b8)(on b8 b7)(on b7 b3)(on b3 b9)(on b9 b6)(on b6 b5)(on b5 b10)(on b10 b2)(on-table b2)))
)