; Generated by PTT
(define (problem blocksworld_12)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 - object
)
(:init (arm-empty)(clear b12)(on b12 b3)(on b3 b1)(on b1 b8)(on b8 b5)(on b5 b13)(on b13 b9)(on-table b9)(clear b10)(on b10 b6)(on b6 b4)(on b4 b2)(on b2 b14)(on b14 b11)(on b11 b7)(on-table b7)(stag_on b13 b7)(stag_on b7 b5)(stag_on b5 b9)(stag_on b9 b11)(stag_on b11 b3)(stag_on b3 b12)(stag_on b12 b8)(stag_on b10 b14)(stag_on b14 b1)(stag_on b1 b4)(stag_on b4 b2)(stag_on b2 b6))
(:goal (and  (clear b13)(on b13 b7)(on b7 b5)(on b5 b9)(on b9 b11)(on b11 b3)(on b3 b12)(on b12 b8)(on-table b8)(clear b10)(on b10 b14)(on b14 b1)(on b1 b4)(on b4 b2)(on b2 b6)(on-table b6)))
)