; Generated by PTT
(define (problem blocksworld_13)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 - object
)
(:init (arm-empty)(clear b15)(on b15 b14)(on b14 b12)(on b12 b5)(on b5 b10)(on b10 b3)(on-table b3)(clear b7)(on b7 b11)(on b11 b9)(on b9 b8)(on b8 b13)(on b13 b2)(on-table b2)(clear b4)(on b4 b6)(on b6 b1)(on-table b1)(stag_on b6 b12)(stag_on b12 b15)(stag_on b15 b5)(stag_on b5 b1)(stag_on b1 b13)(stag_on b13 b2)(stag_on b2 b8)(stag_on b8 b14)(stag_on b14 b7)(stag_on b7 b11)(stag_on b11 b9)(stag_on b9 b4)(stag_on b4 b10)(stag_on b10 b3))
(:goal (and  (clear b6)(on b6 b12)(on b12 b15)(on b15 b5)(on b5 b1)(on b1 b13)(on b13 b2)(on b2 b8)(on b8 b14)(on b14 b7)(on b7 b11)(on b11 b9)(on b9 b4)(on b4 b10)(on b10 b3)(on-table b3)))
)