; Generated by PTT
(define (problem blocksworld_14)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 - object
)
(:init (arm-empty)(clear b14)(on b14 b15)(on b15 b12)(on-table b12)(clear b4)(on b4 b6)(on b6 b13)(on-table b13)(clear b9)(on b9 b11)(on b11 b5)(on b5 b3)(on b3 b10)(on b10 b7)(on b7 b8)(on b8 b1)(on b1 b2)(on-table b2)(stag_on b5 b10)(stag_on b10 b12)(stag_on b12 b3)(stag_on b3 b6)(stag_on b6 b11)(stag_on b4 b14)(stag_on b14 b1)(stag_on b1 b8)(stag_on b8 b2)(stag_on b2 b9)(stag_on b9 b15)(stag_on b15 b13)(stag_on b13 b7))
(:goal (and  (clear b5)(on b5 b10)(on b10 b12)(on b12 b3)(on b3 b6)(on b6 b11)(on-table b11)(clear b4)(on b4 b14)(on b14 b1)(on b1 b8)(on b8 b2)(on b2 b9)(on b9 b15)(on b15 b13)(on b13 b7)(on-table b7)))
)