; Generated by PTT
(define (problem blocksworld_16)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 b16 b17 - object
)
(:init (arm-empty)(clear b17)(on b17 b8)(on b8 b11)(on b11 b3)(on b3 b1)(on b1 b4)(on b4 b16)(on-table b16)(clear b13)(on b13 b12)(on b12 b9)(on b9 b7)(on-table b7)(clear b2)(on b2 b6)(on b6 b10)(on b10 b15)(on b15 b14)(on b14 b5)(on-table b5)(stag_on b3 b13)(stag_on b13 b1)(stag_on b1 b14)(stag_on b14 b7)(stag_on b7 b5)(stag_on b5 b6)(stag_on b6 b4)(stag_on b4 b17)(stag_on b17 b11)(stag_on b11 b2)(stag_on b2 b10)(stag_on b10 b15)(stag_on b15 b9)(stag_on b9 b8)(stag_on b8 b12)(stag_on b12 b16))
(:goal (and  (clear b3)(on b3 b13)(on b13 b1)(on b1 b14)(on b14 b7)(on b7 b5)(on b5 b6)(on b6 b4)(on b4 b17)(on b17 b11)(on b11 b2)(on b2 b10)(on b10 b15)(on b15 b9)(on b9 b8)(on b8 b12)(on b12 b16)(on-table b16)))
)