; Generated by PTT
(define (problem blocksworld_24)(:domain blocksworld)
(:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 b16 b17 b18 b19 b20 b21 b22 b23 b24 - object
)
(:init (arm-empty)(clear b22)(on b22 b24)(on-table b24)(clear b5)(on b5 b12)(on b12 b21)(on b21 b19)(on-table b19)(clear b23)(on b23 b9)(on b9 b18)(on b18 b10)(on b10 b1)(on b1 b4)(on b4 b16)(on b16 b11)(on b11 b8)(on b8 b3)(on b3 b13)(on-table b13)(clear b17)(on b17 b15)(on b15 b7)(on b7 b6)(on b6 b20)(on b20 b14)(on b14 b2)(on-table b2)(stag_on b17 b15)(stag_on b15 b21)(stag_on b21 b18)(stag_on b18 b12)(stag_on b12 b4)(stag_on b4 b19)(stag_on b19 b7)(stag_on b7 b3)(stag_on b3 b8)(stag_on b8 b24)(stag_on b24 b10)(stag_on b10 b5)(stag_on b5 b22)(stag_on b22 b23)(stag_on b23 b9)(stag_on b9 b14)(stag_on b14 b1)(stag_on b1 b11)(stag_on b11 b2)(stag_on b2 b6)(stag_on b6 b16)(stag_on b16 b20))
(:goal (and  (clear b13)(on-table b13)(clear b17)(on b17 b15)(on b15 b21)(on b21 b18)(on b18 b12)(on b12 b4)(on b4 b19)(on b19 b7)(on b7 b3)(on b3 b8)(on b8 b24)(on b24 b10)(on b10 b5)(on b5 b22)(on b22 b23)(on b23 b9)(on b9 b14)(on b14 b1)(on b1 b11)(on b11 b2)(on b2 b6)(on b6 b16)(on b16 b20)(on-table b20)))
)