; Generated by PTT
(define (domain sokoban)
(:requirements :typing :equality)
(:types location direction box - object
)
(:constants down up left right - direction
)
(:predicates (at-robot ?l - location)
(at ?o - box ?l - location)
(adjacent ?l1 - location ?l2 - location ?d - direction)
(clear ?l - location)
(stai_clear ?floc - location)
)
(:action move
:parameters ( ?from - location ?to - location ?dir - direction)
:precondition (and (clear ?to)(at-robot ?from)(adjacent ?from ?to ?dir))
:effect (and (at-robot ?to)(not (at-robot ?from)))
)
(:action push
:parameters ( ?rloc - location ?bloc - location ?floc - location ?dir - direction ?b - box)
:precondition (and (at-robot ?rloc)(at ?b ?bloc)(clear ?floc)(adjacent ?rloc ?bloc ?dir)(adjacent ?bloc ?floc ?dir))
:effect (and (at-robot ?bloc)(at ?b ?floc)(clear ?bloc)(not (at-robot ?rloc))(not (at ?b ?bloc))(not (clear ?floc)))
)
(:action push_mcr_push
:parameters ( ?rloc - location ?bloc - location ?floc - location ?dir - direction ?b - box ?flocx5 - location)
:precondition (and (at-robot ?rloc)(at ?b ?bloc)(clear ?floc)(adjacent ?rloc ?bloc ?dir)(adjacent ?bloc ?floc ?dir)(clear ?flocx5)(adjacent ?floc ?flocx5 ?dir)(stai_clear ?floc)(stai_clear ?flocx5)(not (= ?floc ?flocx5)))
:effect (and (clear ?bloc)(at-robot ?floc)(at ?b ?flocx5)(clear ?floc)(not (at-robot ?rloc))(not (at ?b ?bloc))(not (at-robot ?bloc))(not (at ?b ?floc))(not (clear ?flocx5)))
)
)