; Generated by PTT
(define (domain blocksworld)
(:requirements :typing :equality)
(:types object
)
(:predicates (clear ?x - object)
(on-table ?x - object)
(arm-empty)
(holding ?x - object)
(on ?x - object ?y - object)
(stag_on ?ob - object ?underobx1 - object)
)
(:action pickup
:parameters ( ?ob - object)
:precondition (and (clear ?ob)(on-table ?ob)(arm-empty))
:effect (and (holding ?ob)(not (clear ?ob))(not (on-table ?ob))(not (arm-empty)))
)
(:action putdown
:parameters ( ?ob - object)
:precondition (and (holding ?ob))
:effect (and (clear ?ob)(arm-empty)(on-table ?ob)(not (holding ?ob)))
)
(:action stack
:parameters ( ?ob - object ?underob - object)
:precondition (and (clear ?underob)(holding ?ob))
:effect (and (arm-empty)(clear ?ob)(on ?ob ?underob)(not (clear ?underob))(not (holding ?ob)))
)
(:action unstack
:parameters ( ?ob - object ?underob - object)
:precondition (and (on ?ob ?underob)(clear ?ob)(arm-empty))
:effect (and (holding ?ob)(clear ?underob)(not (on ?ob ?underob))(not (clear ?ob))(not (arm-empty)))
)
(:action pickup_mcr_stack
:parameters ( ?ob - object ?underobx1 - object)
:precondition (and (clear ?ob)(on-table ?ob)(arm-empty)(clear ?underobx1)(stag_on ?ob ?underobx1)(not (= ?ob ?underobx1)))
:effect (and (arm-empty)(clear ?ob)(on ?ob ?underobx1)(not (on-table ?ob))(not (clear ?underobx1))(not (holding ?ob)))
)
)