; Generated by PTT
(define (domain transport)
(:requirements :typing :equality)
(:types location target locatable - object
 vehicle package - locatable
 capacity-number - object
)
(:predicates (road ?l1 - location ?l2 - location)
(at ?x - locatable ?v - location)
(in ?x - package ?v - vehicle)
(capacity ?v - vehicle ?s1 - capacity-number)
(capacity-predecessor ?s1 - capacity-number ?s2 - capacity-number)
(stag_at ?px6 - package ?l2x5 - location)
)
(:functions (road-length ?l1 - location ?l2 - location)
(total-cost)
)
(:action drive
:parameters ( ?v - vehicle ?l1 - location ?l2 - location)
:precondition (and (at ?v ?l1)(road ?l1 ?l2))
:effect (and (not (at ?v ?l1))(at ?v ?l2)(increase (total-cost) 20))
)
(:action pick-up
:parameters ( ?v - vehicle ?l - location ?p - package ?s1 - capacity-number ?s2 - capacity-number)
:precondition (and (at ?v ?l)(at ?p ?l)(capacity-predecessor ?s1 ?s2)(capacity ?v ?s2))
:effect (and (not (at ?p ?l))(in ?p ?v)(capacity ?v ?s1)(not (capacity ?v ?s2))(increase (total-cost) 1))
)
(:action drop
:parameters ( ?v - vehicle ?l - location ?p - package ?s1 - capacity-number ?s2 - capacity-number)
:precondition (and (at ?v ?l)(in ?p ?v)(capacity-predecessor ?s1 ?s2)(capacity ?v ?s1))
:effect (and (not (in ?p ?v))(at ?p ?l)(capacity ?v ?s2)(not (capacity ?v ?s1))(increase (total-cost) 1))
)
(:action pick-up_mcr_drive_mcr_drop
:parameters ( ?v - vehicle ?l - location ?p - package ?s1 - capacity-number ?s2 - capacity-number ?l2x5 - location ?px6 - package)
:precondition (and (at ?v ?l)(at ?p ?l)(capacity-predecessor ?s1 ?s2)(capacity ?v ?s2)(road ?l ?l2x5)(in ?px6 ?v)(stag_at ?px6 ?l2x5)(not (= ?v ?p)))
:effect (and (in ?p ?v)(at ?v ?l2x5)(at ?px6 ?l2x5)(capacity ?v ?s2)(not (at ?p ?l))(not (at ?v ?l))(not (in ?px6 ?v))(not (capacity ?v ?s1))(increase (total-cost) 22))
)
(:action drop_mcr_drive_mcr_pick-up
:parameters ( ?v - vehicle ?l - location ?p - package ?s1 - capacity-number ?s2 - capacity-number ?l2x5 - location ?px6 - package)
:precondition (and (at ?v ?l)(in ?p ?v)(capacity-predecessor ?s1 ?s2)(capacity ?v ?s1)(road ?l ?l2x5)(at ?px6 ?l2x5)(stag_at ?p ?l)(not (= ?v ?px6))(not (= ?l ?l2x5)))
:effect (and (at ?p ?l)(at ?v ?l2x5)(in ?px6 ?v)(capacity ?v ?s1)(not (in ?p ?v))(not (at ?v ?l))(not (at ?px6 ?l2x5))(not (capacity ?v ?s2))(increase (total-cost) 22))
)
)