; Generated by PTT
(define (problem ferry_01)(:domain ferry)
(:objects  car1 car2 - car
 loc1 loc2 loc3 loc4 loc5 - location
)
(:init (empty-ferry)(at-ferry loc1)(at car1 loc5)(at car2 loc2)(stai_at car1 loc5)(stai_at car2 loc2)(stag_at car1 loc3)(stag_at car2 loc3))
(:goal (and  (at car1 loc3)(at car2 loc3)))
)