; Generated by PTT
(define (problem ferry_09)(:domain ferry)
(:objects  car1 car2 car3 car4 car5 car6 car7 - car
 loc1 loc2 loc3 loc4 loc5 loc6 loc7 - location
)
(:init (empty-ferry)(at-ferry loc1)(at car1 loc7)(at car2 loc3)(at car3 loc4)(at car4 loc5)(at car5 loc6)(at car6 loc7)(at car7 loc7)(stai_at car1 loc7)(stai_at car2 loc3)(stai_at car3 loc4)(stai_at car4 loc5)(stai_at car5 loc6)(stai_at car6 loc7)(stai_at car7 loc7)(stag_at car1 loc6)(stag_at car2 loc5)(stag_at car3 loc3)(stag_at car4 loc4)(stag_at car5 loc5)(stag_at car6 loc6)(stag_at car7 loc3))
(:goal (and  (at car1 loc6)(at car2 loc5)(at car3 loc3)(at car4 loc4)(at car5 loc5)(at car6 loc6)(at car7 loc3)))
)