; Generated by PTT
(define (problem ferry_11)(:domain ferry)
(:objects  car1 car2 car3 car4 car5 car6 car7 car8 - car
 loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 - location
)
(:init (empty-ferry)(at-ferry loc8)(at car1 loc7)(at car2 loc4)(at car3 loc2)(at car4 loc6)(at car5 loc5)(at car6 loc2)(at car7 loc5)(at car8 loc5)(stai_at car1 loc7)(stai_at car2 loc4)(stai_at car3 loc2)(stai_at car4 loc6)(stai_at car5 loc5)(stai_at car6 loc2)(stai_at car7 loc5)(stai_at car8 loc5)(stag_at car1 loc8)(stag_at car2 loc8)(stag_at car3 loc8)(stag_at car4 loc1)(stag_at car5 loc7)(stag_at car6 loc4)(stag_at car7 loc8)(stag_at car8 loc4))
(:goal (and  (at car1 loc8)(at car2 loc8)(at car3 loc8)(at car4 loc1)(at car5 loc7)(at car6 loc4)(at car7 loc8)(at car8 loc4)))
)