; Generated by PTT
(define (problem ferry_16)(:domain ferry)
(:objects  car1 car2 car3 car4 car5 car6 car7 car8 car9 car10 car11 - car
 loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 - location
)
(:init (empty-ferry)(at-ferry loc3)(at car1 loc7)(at car2 loc10)(at car3 loc6)(at car4 loc2)(at car5 loc7)(at car6 loc9)(at car7 loc2)(at car8 loc6)(at car9 loc4)(at car10 loc7)(at car11 loc1)(stai_at car1 loc7)(stai_at car2 loc10)(stai_at car3 loc6)(stai_at car4 loc2)(stai_at car5 loc7)(stai_at car6 loc9)(stai_at car7 loc2)(stai_at car8 loc6)(stai_at car9 loc4)(stai_at car10 loc7)(stai_at car11 loc1)(stag_at car1 loc5)(stag_at car2 loc8)(stag_at car3 loc5)(stag_at car4 loc8)(stag_at car5 loc6)(stag_at car6 loc2)(stag_at car7 loc4)(stag_at car8 loc8)(stag_at car9 loc9)(stag_at car10 loc1)(stag_at car11 loc4))
(:goal (and  (at car1 loc5)(at car2 loc8)(at car3 loc5)(at car4 loc8)(at car5 loc6)(at car6 loc2)(at car7 loc4)(at car8 loc8)(at car9 loc9)(at car10 loc1)(at car11 loc4)))
)